[package]
name = "enose_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
influxdb2 = "0.5.0" # Client InfluxDB yang modern
chrono = "0.4"
futures = "0.3"
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1.0"